//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANNER
    {
        public int BannerId { get; set; }
        public string ImageUrl { get; set; }
        public string AdminImagePath { get; set; }
        public string BannerTitle { get; set; }
        public string Description { get; set; }
        public string BannerType { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
