//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeNewTest
    {
        public short LOCNO { get; set; }
        public int ITEM_CODE { get; set; }
        public short PACK_CODE { get; set; }
        public string PACK_DESC { get; set; }
        public decimal UNIT { get; set; }
        public bool bDEFAULT { get; set; }
        public string BAR_CODE { get; set; }
        public byte BARTYPE { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public decimal DEALER_PRICE1 { get; set; }
        public decimal DEALER_PRICE2 { get; set; }
        public decimal RF_MARGIN { get; set; }
        public int CUSER { get; set; }
        public System.DateTime CDATE { get; set; }
        public int MUSER { get; set; }
        public System.DateTime MDATE { get; set; }
        public bool bRandomDisc { get; set; }
        public System.DateTime DiscStartDate { get; set; }
        public System.DateTime DiscEndDate { get; set; }
        public System.DateTime DiscStartTime { get; set; }
        public System.DateTime DiscEndTime { get; set; }
        public short DISC_TYPE { get; set; }
        public decimal DISC { get; set; }
        public bool IsActive { get; set; }
        public bool NeedsReplication { get; set; }
        public bool NeedsUpdation { get; set; }
        public Nullable<bool> L1P1NeedsUpdation { get; set; }
        public Nullable<bool> L1P2NeedsUpdation { get; set; }
        public Nullable<bool> L1P3NeedsUpdation { get; set; }
        public Nullable<bool> L1P4NeedsUpdation { get; set; }
        public Nullable<bool> L1P5NeedsUpdation { get; set; }
        public Nullable<bool> L1P6NeedsUpdation { get; set; }
        public Nullable<bool> L1P7NeedsUpdation { get; set; }
        public Nullable<bool> L1P8NeedsUpdation { get; set; }
        public Nullable<bool> L1P9NeedsUpdation { get; set; }
        public Nullable<bool> L1P10NeedsUpdation { get; set; }
        public Nullable<bool> L2P1NeedsUpdation { get; set; }
        public Nullable<bool> L2P2NeedsUpdation { get; set; }
        public Nullable<bool> L2P3NeedsUpdation { get; set; }
        public Nullable<bool> L3P1NeedsUpdation { get; set; }
        public Nullable<bool> L3P2NeedsUpdation { get; set; }
        public Nullable<bool> L3P3NeedsUpdation { get; set; }
        public Nullable<bool> L3P4NeedsUpdation { get; set; }
        public Nullable<bool> L3P5NeedsUpdation { get; set; }
        public Nullable<bool> L3P6NeedsUpdation { get; set; }
        public Nullable<bool> L3P7NeedsUpdation { get; set; }
        public Nullable<bool> L3P8NeedsUpdation { get; set; }
        public Nullable<bool> L4P1NeedsUpdation { get; set; }
        public Nullable<bool> L5P1NeedsUpdation { get; set; }
        public Nullable<bool> L6P1NeedsUpdation { get; set; }
        public Nullable<bool> L4P2NeedsUpdation { get; set; }
        public Nullable<bool> L4P3NeedsUpdation { get; set; }
        public Nullable<bool> L5P3NeedsUpdation { get; set; }
        public Nullable<bool> L6P3NeedsUpdation { get; set; }
        public Nullable<bool> L5P2NeedsUpdation { get; set; }
        public Nullable<bool> L6P2NeedsUpdation { get; set; }
    }
}
