//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BARCODE
    {
        public short LOCNO { get; set; }
        public int ITEM_CODE { get; set; }
        public short PACK_CODE { get; set; }
        public string PACK_DESC { get; set; }
        public decimal UNIT { get; set; }
        public bool bDEFAULT { get; set; }
        public string BAR_CODE { get; set; }
        public short BARTYPE { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public decimal DEALER_PRICE1 { get; set; }
        public decimal DEALER_PRICE2 { get; set; }
        public decimal RF_MARGIN { get; set; }
        public int CUSER { get; set; }
        public System.DateTime CDATE { get; set; }
        public int MUSER { get; set; }
        public System.DateTime MDATE { get; set; }
        public bool bRandomDisc { get; set; }
        public System.DateTime DiscStartDate { get; set; }
        public System.DateTime DiscEndDate { get; set; }
        public System.DateTime DiscStartTime { get; set; }
        public System.DateTime DiscEndTime { get; set; }
        public short DISC_TYPE { get; set; }
        public decimal DISC { get; set; }
        public decimal LOYALTY_DISC { get; set; }
        public decimal STAFF_DISC { get; set; }
        public bool IsActive { get; set; }
    }
}
