//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public int CART_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
