//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string WebsiteTitle { get; set; }
        public string BottomText { get; set; }
        public string BottomLogoUrl { get; set; }
        public string TopLogoUrl { get; set; }
        public string SocialVimeoUrl { get; set; }
        public string SocialPinterestUrl { get; set; }
        public string SocialTwitterUrl { get; set; }
        public string SocialFacebookUrl { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string AboutUsText { get; set; }
        public string IosAppUrl { get; set; }
        public string AndroidAppUrl { get; set; }
    }
}
