//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        public int GROUP_ID { get; set; }
        public string NAME { get; set; }
        public string IMAGE_NAME { get; set; }
        public string RELATIVE_IMAGE_NAME { get; set; }
        public string NAME_URL { get; set; }
    }
}
