//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemList
    {
        public Nullable<int> CATEGORY_ID { get; set; }
        public string Category { get; set; }
        public Nullable<int> SUB_CATEGORY_ID { get; set; }
        public string SubCategory { get; set; }
        public int PRODUCT_ID { get; set; }
        public string BAR_CODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
    }
}
