//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMINFO
    {
        public int ITEM_CODE { get; set; }
        public string HV_CODE { get; set; }
        public Nullable<byte> ITEM_ATTRIB { get; set; }
        public Nullable<byte> ITEM_TYPE { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> PACKING_UNITS { get; set; }
        public Nullable<bool> ISSUE_BY_WEIGHT { get; set; }
        public string ITEM_DESC { get; set; }
        public string ITEM_DESC_LONG { get; set; }
        public Nullable<int> SECTID { get; set; }
        public Nullable<short> DEPT_CODE { get; set; }
        public Nullable<short> GRCODE { get; set; }
        public Nullable<short> SUBGRCODE { get; set; }
        public Nullable<int> CATCODE { get; set; }
        public Nullable<int> BRAND_CODE { get; set; }
        public Nullable<int> DESIGN_CD { get; set; }
        public Nullable<short> CLR_CODE { get; set; }
        public Nullable<short> MAKE_CODE { get; set; }
        public Nullable<int> SIZE_CODE { get; set; }
        public Nullable<int> AUTH_CODE { get; set; }
        public Nullable<int> PUB_CODE { get; set; }
        public string EDITION { get; set; }
        public string CLASS { get; set; }
        public string ISBN { get; set; }
        public string SEX { get; set; }
        public string SEASON { get; set; }
        public string AGE { get; set; }
        public string FABRIC { get; set; }
        public Nullable<bool> IsPACKAGE { get; set; }
        public Nullable<bool> IsRECIPE { get; set; }
        public Nullable<bool> SERIALIZED { get; set; }
        public Nullable<bool> FEATURED { get; set; }
        public Nullable<bool> EXPIRY_ITEM { get; set; }
        public string COMMENT { get; set; }
        public Nullable<bool> EXEMPT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> GST_SALES { get; set; }
        public Nullable<byte> GST_MODE { get; set; }
        public string GST_REF { get; set; }
        public string HS_CODE { get; set; }
        public Nullable<decimal> GROSS_WEIGHT { get; set; }
        public Nullable<decimal> NET_WEIGHT { get; set; }
        public Nullable<bool> OPEN_PRICE { get; set; }
        public Nullable<bool> FRACTIONAL { get; set; }
        public Nullable<bool> ALLOWQTY { get; set; }
        public Nullable<decimal> BATCH_QTY { get; set; }
        public Nullable<decimal> ITEM_DISC { get; set; }
        public Nullable<bool> bDISCOUNTED { get; set; }
        public Nullable<decimal> DISC_QTY { get; set; }
        public Nullable<decimal> SALE_DISC { get; set; }
        public Nullable<bool> bPrintOnBill { get; set; }
        public string DESCR { get; set; }
        public string IMAGE_PATH { get; set; }
        public string THUMBNAIL_PATH { get; set; }
        public Nullable<bool> IMPORTED { get; set; }
        public Nullable<bool> ShowOnWeb { get; set; }
        public Nullable<bool> bNEW { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<int> CUSER { get; set; }
        public Nullable<System.DateTime> MDATE { get; set; }
        public Nullable<int> MUSER { get; set; }
        public Nullable<short> CreatedAt { get; set; }
        public Nullable<bool> NeedsReplication { get; set; }
        public Nullable<bool> L1P1NeedsUpdation { get; set; }
        public Nullable<bool> L1P2NeedsUpdation { get; set; }
        public Nullable<bool> L1P3NeedsUpdation { get; set; }
        public Nullable<bool> L1P4NeedsUpdation { get; set; }
        public Nullable<bool> L1P5NeedsUpdation { get; set; }
        public Nullable<bool> L1P6NeedsUpdation { get; set; }
        public Nullable<bool> L1P7NeedsUpdation { get; set; }
        public Nullable<bool> L1P8NeedsUpdation { get; set; }
        public Nullable<bool> L1P9NeedsUpdation { get; set; }
        public Nullable<bool> L1P10NeedsUpdation { get; set; }
        public Nullable<bool> L2P1NeedsUpdation { get; set; }
        public Nullable<bool> L2P2NeedsUpdation { get; set; }
        public Nullable<bool> L2P3NeedsUpdation { get; set; }
        public Nullable<bool> L3P1NeedsUpdation { get; set; }
        public Nullable<bool> L3P2NeedsUpdation { get; set; }
        public Nullable<bool> L3P3NeedsUpdation { get; set; }
        public Nullable<bool> L3P4NeedsUpdation { get; set; }
        public Nullable<bool> L3P5NeedsUpdation { get; set; }
        public Nullable<bool> L3P6NeedsUpdation { get; set; }
        public Nullable<bool> L3P7NeedsUpdation { get; set; }
        public Nullable<bool> L3P8NeedsUpdation { get; set; }
        public Nullable<bool> L4P1NeedsUpdation { get; set; }
        public Nullable<bool> L5P1NeedsUpdation { get; set; }
        public Nullable<bool> L6P1NeedsUpdation { get; set; }
        public Nullable<bool> L4P2NeedsUpdation { get; set; }
        public Nullable<bool> L4P3NeedsUpdation { get; set; }
        public Nullable<bool> L5P3NeedsUpdation { get; set; }
        public Nullable<bool> L6P3NeedsUpdation { get; set; }
        public Nullable<bool> L5P2NeedsUpdation { get; set; }
        public Nullable<bool> L6P2NeedsUpdation { get; set; }
        public Nullable<bool> L1P11NeedsUpdation { get; set; }
        public Nullable<bool> L1P12NeedsUpdation { get; set; }
        public Nullable<bool> L3P9NeedsUpdation { get; set; }
        public Nullable<bool> L3P10NeedsUpdation { get; set; }
        public Nullable<bool> L4P4NeedsUpdation { get; set; }
        public Nullable<bool> L4P5NeedsUpdation { get; set; }
        public Nullable<bool> L5P4NeedsUpdation { get; set; }
        public Nullable<bool> L5P5NeedsUpdation { get; set; }
        public Nullable<bool> L6P4NeedsUpdation { get; set; }
        public Nullable<bool> L6P5NeedsUpdation { get; set; }
        public Nullable<bool> L7P1NeedsUpdation { get; set; }
        public Nullable<bool> L7P2NeedsUpdation { get; set; }
        public Nullable<bool> L7P3NeedsUpdation { get; set; }
        public Nullable<bool> L7P4NeedsUpdation { get; set; }
        public Nullable<bool> L7P5NeedsUpdation { get; set; }
        public Nullable<bool> L7P6NeedsUpdation { get; set; }
        public Nullable<bool> L7P7NeedsUpdation { get; set; }
        public Nullable<bool> L7P8NeedsUpdation { get; set; }
        public Nullable<bool> L2P4NeedsUpdation { get; set; }
        public Nullable<bool> L2P5NeedsUpdation { get; set; }
        public Nullable<bool> L2P6NeedsUpdation { get; set; }
        public Nullable<bool> L2P7NeedsUpdation { get; set; }
        public Nullable<bool> L2P8NeedsUpdation { get; set; }
        public Nullable<bool> L2P9NeedsUpdation { get; set; }
        public Nullable<bool> L2P10NeedsUpdation { get; set; }
        public Nullable<bool> L0NeedsUpdation { get; set; }
        public Nullable<bool> L1NeedsUpdation { get; set; }
        public Nullable<bool> L2NeedsUpdation { get; set; }
        public Nullable<bool> L3NeedsUpdation { get; set; }
        public Nullable<bool> L4NeedsUpdation { get; set; }
        public Nullable<bool> L5NeedsUpdation { get; set; }
        public Nullable<bool> L6NeedsUpdation { get; set; }
        public Nullable<bool> L4P6NeedsUpdation { get; set; }
        public Nullable<bool> L5P6NeedsUpdation { get; set; }
        public Nullable<bool> L6P6NeedsUpdation { get; set; }
        public Nullable<bool> L7NeedsUpdation { get; set; }
        public Nullable<bool> L8NeedsUpdation { get; set; }
        public Nullable<bool> L9NeedsUpdation { get; set; }
        public Nullable<bool> L10NeedsUpdation { get; set; }
        public Nullable<bool> L11NeedsUpdation { get; set; }
        public Nullable<bool> L12NeedsUpdation { get; set; }
        public Nullable<bool> L8P1NeedsUpdation { get; set; }
        public Nullable<bool> L9P1NeedsUpdation { get; set; }
        public Nullable<bool> L10P1NeedsUpdation { get; set; }
        public Nullable<bool> L11P1NeedsUpdation { get; set; }
        public Nullable<bool> L12P1NeedsUpdation { get; set; }
        public Nullable<bool> L8P2NeedsUpdation { get; set; }
        public Nullable<bool> L8p3NeedsUpdation { get; set; }
    }
}
