//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFER_MANAGEMENT
    {
        public int OFFER_ID { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public Nullable<int> SUB_CATEGORY_ID { get; set; }
        public string SUB_CATEGORY_NAME { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
