//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_IMAGES
    {
        public int PRODUCT_IMAGE_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string ADMIN_IMAGE_PATH { get; set; }
        public string ADMIN_THUMNAIL_IMAGE_PATH { get; set; }
        public string CHAARSU_IMAGE_PATH { get; set; }
        public string CHAARSU_THUMBNAIL_PATH { get; set; }
    }
}
