//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_LEVELS
    {
        public int PRODUCT_LEVEL_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> SUB_CATEGORY_ID { get; set; }
    }
}
