//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS000Test
    {
        public short LOCNO { get; set; }
        public int ITEM_CODE { get; set; }
        public decimal QTY { get; set; }
        public decimal WH_QTY { get; set; }
        public decimal T_QTY { get; set; }
        public byte FLOOR_NO { get; set; }
        public short COUNTER { get; set; }
        public byte SHELF { get; set; }
        public decimal SHELF_QTY { get; set; }
        public decimal SHELF_FACING { get; set; }
        public System.DateTime LSDATE { get; set; }
        public System.DateTime LPDATE { get; set; }
        public bool ALLOW_NEGATIVE { get; set; }
        public decimal AreaCovered { get; set; }
        public bool IsActive { get; set; }
        public decimal MAX_QTY { get; set; }
        public decimal MIN_QTY { get; set; }
        public decimal OP_STOCK { get; set; }
        public decimal OP_STOCK_VAL { get; set; }
        public bool NeedsReplication { get; set; }
        public bool NeedsUpdation { get; set; }
    }
}
