//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECOMMENDED_PRODUCTS
    {
        public int RECOMMENDED_PRODUCT_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string PACKING { get; set; }
        public string TYPE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    }
}
