//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ORDER_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string NAME { get; set; }
        public string MOBILE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string PROD_NAME { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    }
}
