//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIDER_ORDER
    {
        public int RIDER_ORDER_ID { get; set; }
        public Nullable<int> RIDER_ID { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public string RIDER_TIME_IN { get; set; }
        public string RIDER_TIME_OUT { get; set; }
        public Nullable<bool> IS_RIDER_BACK { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
