//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_CATEGORIES
    {
        public int SUB_CATEGORY_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IsActive { get; set; }
        public string APP_IMAGE_PATH { get; set; }
        public string DESCRIPTION_URL { get; set; }
    }
}
