//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBMENU
    {
        public int ID { get; set; }
        public string SUBMENU1 { get; set; }
        public int MAINMENUID { get; set; }
        public int USERTYPEID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
