//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERMINFO
    {
        public short LOCNO { get; set; }
        public short TERM_NO { get; set; }
        public byte TERM_TYPE { get; set; }
        public long FBR_POSNO { get; set; }
        public bool FBR_ENABLED { get; set; }
        public string HEAD0 { get; set; }
        public string HEAD1 { get; set; }
        public string HEAD2 { get; set; }
        public string HEAD3 { get; set; }
        public string HEAD4 { get; set; }
        public string TAIL0 { get; set; }
        public string TAIL1 { get; set; }
        public string TAIL2 { get; set; }
        public string TAIL3 { get; set; }
        public string TAIL4 { get; set; }
        public byte PLINES { get; set; }
        public double PRT_PORT { get; set; }
        public short FLOOR { get; set; }
        public bool RUNNING { get; set; }
        public string PRTDEV { get; set; }
        public string PRTDEV1 { get; set; }
        public byte RCPT_TYPE { get; set; }
        public byte PRT_TYPE { get; set; }
        public byte PRT_ALLIGN { get; set; }
        public int PRT_LMARGIN { get; set; }
        public int PRT_TMARGIN { get; set; }
        public byte CDR_TYPE { get; set; }
        public byte CDISP_TYPE { get; set; }
        public bool CDR_ENABLED { get; set; }
        public bool CDISP_ENABLED { get; set; }
        public int CDR_PORT { get; set; }
        public string CDISP_PORT { get; set; }
        public int USERID { get; set; }
        public int MAXORD { get; set; }
        public int MAXDOC { get; set; }
        public System.DateTime LAST_UPDATED { get; set; }
        public string COL1 { get; set; }
        public string COL2 { get; set; }
        public string COL3 { get; set; }
        public string COL4 { get; set; }
        public System.DateTime LSDate { get; set; }
        public System.DateTime LRDate { get; set; }
        public bool IsActive { get; set; }
        public bool NeedsUpdation { get; set; }
        public bool NeedsReplication { get; set; }
        public bool L1P1NeedsUpdation { get; set; }
        public bool L1P2NeedsUpdation { get; set; }
        public bool L1P3NeedsUpdation { get; set; }
        public bool L9P1NeedsUpdation { get; set; }
        public bool L10P1NeedsUpdation { get; set; }
        public bool L11P1NeedsUpdation { get; set; }
        public bool L12P1NeedsUpdation { get; set; }
        public bool L1P7NeedsUpdation { get; set; }
        public bool L1P8NeedsUpdation { get; set; }
        public bool L1P9NeedsUpdation { get; set; }
        public bool L1P10NeedsUpdation { get; set; }
        public bool L1P11NeedsUpdation { get; set; }
        public bool L1P12NeedsUpdation { get; set; }
        public bool L2P1NeedsUpdation { get; set; }
        public bool L2P2NeedsUpdation { get; set; }
        public bool L2P3NeedsUpdation { get; set; }
        public bool L2P4NeedsUpdation { get; set; }
        public bool L2P5NeedsUpdation { get; set; }
        public bool L2P6NeedsUpdation { get; set; }
        public bool L2P7NeedsUpdation { get; set; }
        public bool L2P8NeedsUpdation { get; set; }
        public bool L2P9NeedsUpdation { get; set; }
        public bool L2P10NeedsUpdation { get; set; }
        public bool L0NeedsUpdation { get; set; }
        public bool L1NeedsUpdation { get; set; }
        public bool L2NeedsUpdation { get; set; }
        public bool L3NeedsUpdation { get; set; }
        public bool L3P1NeedsUpdation { get; set; }
        public bool L4NeedsUpdation { get; set; }
        public bool L5NeedsUpdation { get; set; }
        public bool L6NeedsUpdation { get; set; }
        public bool L3P2NeedsUpdation { get; set; }
        public bool L3P3NeedsUpdation { get; set; }
        public bool L3P4NeedsUpdation { get; set; }
        public bool L3P5NeedsUpdation { get; set; }
        public bool L3P6NeedsUpdation { get; set; }
        public bool L4P1NeedsUpdation { get; set; }
        public bool L4P2NeedsUpdation { get; set; }
        public bool L4P3NeedsUpdation { get; set; }
        public bool L4P4NeedsUpdation { get; set; }
        public bool L4P5NeedsUpdation { get; set; }
        public bool L4P6NeedsUpdation { get; set; }
        public bool L5P6NeedsUpdation { get; set; }
        public bool L5P1NeedsUpdation { get; set; }
        public bool L5P2NeedsUpdation { get; set; }
        public bool L5P3NeedsUpdation { get; set; }
        public bool L5P4NeedsUpdation { get; set; }
        public bool L5P5NeedsUpdation { get; set; }
        public bool L6P1NeedsUpdation { get; set; }
        public bool L6P2NeedsUpdation { get; set; }
        public bool L6P3NeedsUpdation { get; set; }
        public bool L6P4NeedsUpdation { get; set; }
        public bool L6P5NeedsUpdation { get; set; }
        public bool L6P6NeedsUpdation { get; set; }
        public bool L7NeedsUpdation { get; set; }
        public bool L7P1NeedsUpdation { get; set; }
        public bool L7P2NeedsUpdation { get; set; }
        public bool L7P3NeedsUpdation { get; set; }
        public bool L8P1NeedsUpdation { get; set; }
        public bool L8P2NeedsUpdation { get; set; }
        public bool L8P3NeedsUpdation { get; set; }
        public bool L8NeedsUpdation { get; set; }
        public bool L9NeedsUpdation { get; set; }
        public bool L10NeedsUpdation { get; set; }
        public bool L11NeedsUpdation { get; set; }
        public bool L12NeedsUpdation { get; set; }
    }
}
