//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DEVICES
    {
        public int USER_DEVICE_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string DEVICE_ID { get; set; }
        public string FCM_TOKEN { get; set; }
    }
}
