//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR
    {
        public int VENDOR_ID { get; set; }
        public byte CLIENT_TYPE { get; set; }
        public string VENDOR_NAME { get; set; }
        public string ADDR1 { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string CONT_PERSON1 { get; set; }
        public string TITLE1 { get; set; }
        public string MOBILE1 { get; set; }
        public string PHONE1 { get; set; }
        public string FAX1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY2 { get; set; }
        public string COUNTRY2 { get; set; }
        public string CONT_PERSON2 { get; set; }
        public string TITLE2 { get; set; }
        public string MOBILE2 { get; set; }
        public string PHONE2 { get; set; }
        public string FAX2 { get; set; }
        public string WHATSAPP { get; set; }
        public string EMAIL { get; set; }
        public string URL { get; set; }
        public string NTN { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
