//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_BRANCHES
    {
        public int VENDOR_BRANCH_ID { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public string PHONE { get; set; }
    }
}
